### PR TITLE
add crawl lists

### PR DESCRIPTION
**Pull request by dadak-dom**

### CODE REVIEW

**Review by danielgoldelman — APPROVED** [review]

**Comment by SebastianZimmeck** [comment]
A few questions:

- What protocol did you use to create the lists? 
- Do we have the original lists and metadata (e.g., date of the original list) from which the lists were created?
- In the Australia list line 455, https://becoolrefrigeratedcouriers.com is not an Australian top-level domain site. Please check that we have the correct domain for all sites in all lists.
- When I visit https://pmc.gov.au, I get redirected to https://www.pmc.gov.au/. What does our crawler do in such a situation?
- Are we sure that Ukrainian, Portuguese, and other non-English sites are properly analyzed (especially, for location data types and keywords)? See [@JoeChampeau's comment](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/issues/7#issuecomment-1870984369).

**Comment by dadak-dom** [comment]
@SebastianZimmeck To answer some of your questions:
- I made a Google Doc in the Privacy Pioneer folder that outlines the steps for creating a list, as well as our motivations for each country. It can be found [here](https://docs.google.com/document/d/1z9D1GwRxrvBimc-zLSvZnwlO7d5BD2l1YKaTYenWzgY/edit)
- Yes, the original tranco list is one of the lists that were added to this branch. It's the list that was made available on Nov. 27th, 2023.
- That's strange, that site shouldn't be there... I'll do another pass on the lists at some point and make sure that they're all good. That one must have slipped through somehow.
- Daniel addressed this point in our last meeting, that such redirects are not a problem for the crawler
- We will be looking into keywords over the coming days

**Comment by SebastianZimmeck** [comment]
Thanks @dadak-dom!

> Yes, the original tranco list is one of the lists that were added to this branch. It's the list that was made available on Nov. 27th, 2023.

[This is the list](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/tree/issue-7/crawl_lists/tranco_Q9Z84-1m.csv), I assume?

**Comment by dadak-dom** [comment]
Yep, that's the list!

**Comment by danielgoldelman** [comment]
@dadak-dom Are there any other tasks still to do on this pr?

**Comment by dadak-dom** [comment]
@danielgoldelman As far as I knows it should be all good 👍

**Comment by SebastianZimmeck** [comment]
Are the [above points](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/pull/11#issuecomment-1872092762) resolved?

> - In the Australia list line 455, https://becoolrefrigeratedcouriers.com/ is not an Australian top-level domain site. Please check that we have the correct domain for all sites in all lists.
> - Are we sure that Ukrainian, Portuguese, and other non-English sites are properly analyzed (especially, for location data types and keywords)? See https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/issues/7#issuecomment-1870984369.

**Comment by dadak-dom** [comment]
@SebastianZimmeck I've fixed the issue with the list, but the analysis is still in progress.

**Pull request merged**
